spring.application.name=fit

# URL Interna formatada para JDBC (sem usuário e senha na string, e com a porta 5432)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d9fd0drtqb8s73cr8v3g-a:5432/streaks_db_wu58}

# Usuário e Senha
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:streaks_db_wu58_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lQCqdExTHFmwVm1moQapvYTsnXyCN1zZ}

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update